version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: "Installing requirements"
          command: |
            sudo apt update
            sudo apt-get install -y git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison libncurses-dev autoconf dkms libudev-dev libpci-dev libiberty-dev u-boot-tools lzop apt-cacher-ng
      - run:
          name: "Clone repo"
          command: git clone --depth=1 --single-branch -b master https://github.com/SuzukiHonoka/build
      - run:
          name: "Start build"
          no_output_timeout: "1h"
          command: |
            cd build
            ./compile.sh BOARD=rock64 BRANCH=current RELEASE=focal KERNEL_CONFIGURE=no BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_ONLY=no USE_CCACHE=yes
      - store_artifacts:
          path: build/output
