name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: FIX APT SOURCE
        run: sudo sed -i "s/azure.archive.ubuntu.com/www.archive.ubuntu.com/g" /etc/apt/sources.list
      - name: Installing requirements 
        run: |
          sudo apt update
          sudo apt-get install -y git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison libncurses-dev autoconf dkms libudev-dev libpci-dev libiberty-dev u-boot-tools lzop
      - name: Clone repo
        run: git clone --depth=1 --single-branch -b master https://github.com/SuzukiHonoka/build
      - name: Start build
        run: |
          cd build
          ./compile.sh BOARD=rock64 BRANCH=current RELEASE=focal KERNEL_CONFIGURE=no BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_ONLY=no USE_CCACHE=yes
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: build/output 
